### ISSUE TITLE
testUnregisterROIObserver catch Exception

### ISSUE THREAD

**Issue by chrisleee** [benknoble/Comp401-A7#13]
If people have a ConcurrentModificationException in their unregister methods, @benknoble 's testUnregisterROIObservers() in ObservablePictures.java will show up with the message

`legal unregistration of multiple observers by region threw error: null`

It's possible ConcurrentModificationException doesn't have a message which is causing the null (I don't know much about getMessage() to be honest)

Might have to add an extra catch for this error, specifically, with something like:

`catch (ConcurrentModificationException e) {
    fail("legal unregistration of multiple observers by region threw error: " + e); }`

instead of the e.getMessage()

**Comment by benknoble** [comment]
Hmm. The only way to get such an exception is by removing things from a list whilst iterating over it. I know for sure KMPs `NoIntersectionException` has no message; perhaps that's why the "message" is null? Either way, I'll change it to simply print `e`

**Comment by chrisleee** [comment]
Yeah, that's how I initially got the error. I noticed someone else ran into the same issue on Piazza a couple days ago, so it might help others tonight.

Sounds good!
