### ISSUE TITLE
findOberservers test

### ISSUE THREAD

**Issue by ghost** [benknoble/Comp401-A7#3]
I failed this test:
`try {
	    ROIObserver[] r = p.findROIObservers(tiny);
	    assertTrue("observer not found", r != null && r.length == 1 && r[0] == obsB);
	} catch (Exception e) {
	    fail("finding observers threw: " + e.getMessage());
	}
    }`
But I'm not sure if the test is correct.

There are 3 observers:
`p.registerROIObserver(obsA, big);
	p.registerROIObserver(obsA, tiny);
	p.registerROIObserver(obsB, big);`

Big covers the whole picture, from 0,0, to 3,3. Tiny covers an region from 2,2 to 3,3. We're asking findROIObservers to give us an array of all observers that are interested in the region tiny. Both are. Tiny falls within big, so if an observer is interested in big, then it's also interested in tiny. If it's interested in tiny, then it's interested in tiny. 

Why do you think the method should not return obsA, and only obsB?

_findROIObservers(Region r)

This method returns an array of ROIObserver objects (possibly empty) that have registered regions of interest that intersect the given region "r". The same observer object may appear more than once in the result if it happens to be registered more than once with regions of interest that intersect the specified region._

**Comment by benknoble** [comment]
Looks like you caught two errors; one being that it should have been `r[0] == obsA` since that's the one specifically interested in tiny, and one being that I didn't account for regions within regions in that test. 

Post-reflection, I agree with you based on the wording:

> ...regions of interest that intersect...
