### ISSUE TITLE
ObservablePictureTest checking the wrong region

### ISSUE THREAD

**Issue by zburk** [benknoble/Comp401-A7#5]
[Test File](https://github.com/benknoble/Comp401-A7/blob/master/jeroen/ObservablePictureTest.java#L49)

It looks like the test is comparing the entire region being observed `r1` with the region that is changed `o1.getLastRegion()` when it should be comparing the region of the one coordinate `(0, 0)` that changed as stated in the assignment instructions

> So, for example, if we call setPixel on P at position (1,1), then A will be notified once with the region (1,1)->(1,1) as the second argument to the notification method

But I may be reading your `TestROIObserverImpl.java` file wrongly

**Comment by benknoble** [comment]
@zburk what you said makes sense (and looks right to me). If you want to take the initiative and fix it that'd be great; otherwise, I'll get around to it eventually.

Note that I think this happens repeatedly throughout that file... Hm.

**Comment by zburk** [comment]
Awesome I'll fork it and create a fix. I wanted to get another set of eyes on it first before I fixed it.

**Comment by benknoble** [comment]
@zburk looks like I stumbled on it (having forgotten it was broken) and fixed it... Oh well. All my tests pass now!

**Comment by benknoble** [comment]
See [bffcaf](https://github.com/benknoble/Comp401-A7/commit/bffcaf9e565198f5b73de9401b0497dba0c95c74)
